### ISSUE TITLE
How to handle the situation where both modalities are missing?

### ISSUE THREAD

**Issue by XiaokunFeng** [Alexadlu/Modality-missing-RGBT-Tracking#1]
Thank you for your outstanding work. I am in the process of testing my model on the dataset you have provided, and I have encountered an issue that I hope to discuss with you.

In your paper, specifically in Section 3.3, you discuss how the model should track when one modality is missing and when both modalities are present. However, I have noticed instances (some frames) within your dataset where both modalities are missing. I am curious about how you handle such cases.

Do you exclude the results from these frames when evaluating the final metrics? Your guidance on this matter would be greatly appreciated.

Thank you very much for your time and assistance.

**Comment by Alexadlu** [comment]
Thank you for your attention! For the case of dual-modal missing, we have not yet developed a tailored solution in IPL. Currently, our approach involves copying results from the nearest-neighbor historical frames without dual-modal missing to replace the results for the current dual-modal missing frames.

**Comment by XiaokunFeng** [comment]
Got it ,thanks !
